apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-controller
  namespace: mmo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-controller
  template:
    metadata:
      labels:
        app: cell-controller
    spec:
      serviceAccountName: cell-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cell-controller
          image: harbor.pass-k8s.ru/library/mmo-backend:latest
          imagePullPolicy: Always
          command: ["/cell-controller"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          envFrom:
            - secretRef:
                name: mmo-backend
          env:
            - name: MMO_CELL_CONTROLLER_SUBJECT
              value: grid.split.workflow
            - name: MMO_CELL_CONTROLLER_CONTROL_SUBJECT
              value: cell.control
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
